    <div class="passage">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Sagittis orci a scelerisque purus semper eget duis. Non diam phasellus vestibulum lorem sed. Vitae aliquet nec ullamcorper sit amet. Volutpat odio facilisis mauris sit amet massa vitae. Tincidunt praesent semper feugiat nibh sed pulvinar. Cras sed felis eget velit aliquet sagittis id. Purus viverra accumsan in nisl nisi. Odio facilisis mauris sit amet massa.

      At ultrices mi tempus imperdiet. Porttitor lacus luctus accumsan tortor posuere. Neque ornare aenean euismod elementum nisi quis eleifend quam adipiscing. Fames ac turpis egestas maecenas pharetra convallis posuere morbi. Curabitur vitae nunc sed velit dignissim sodales ut eu. Porttitor massa id neque aliquam vestibulum. Et ultrices neque ornare aenean euismod elementum nisi quis eleifend. Vel pretium lectus quam id leo in vitae turpis. At erat pellentesque adipiscing commodo elit at. Nisi quis eleifend quam adipiscing vitae proin sagittis nisl. Nascetur ridiculus mus mauris vitae ultricies leo integer malesuada. Nam libero justo laoreet sit amet cursus sit amet dictum. Amet tellus cras adipiscing enim eu. Amet purus gravida quis blandit turpis cursus in hac.

      Ipsum nunc aliquet bibendum enim facilisis gravida neque convallis. Varius quam quisque id diam. Orci porta non pulvinar neque. Tellus mauris a diam maecenas sed enim ut sem viverra. Aenean pharetra magna ac placerat vestibulum lectus mauris. Mi sit amet mauris commodo. Elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Enim ut sem viverra aliquet eget sit amet. Sed felis eget velit aliquet sagittis id. Malesuada fames ac turpis egestas maecenas pharetra convallis posuere.

      Fringilla est ullamcorper eget nulla facilisi etiam dignissim. Lobortis scelerisque fermentum dui faucibus in ornare quam viverra. Iaculis urna id volutpat lacus. Dictum fusce ut placerat orci nulla. Maecenas pharetra convallis posuere morbi leo urna. Aenean et tortor at risus viverra adipiscing at. Semper quis lectus nulla at volutpat diam ut. Ut sem nulla pharetra diam sit amet nisl suscipit adipiscing. Nulla facilisi cras fermentum odio. Et ligula ullamcorper malesuada proin libero. Tellus cras adipiscing enim eu turpis egestas pretium. Ornare aenean euismod elementum nisi quis eleifend quam adipiscing vitae. Sed arcu non odio euismod lacinia at quis risus. Ultricies lacus sed turpis tincidunt id aliquet. Gravida quis blandit turpis cursus.

      Euismod lacinia at quis risus sed vulputate odio ut. Eget arcu dictum varius duis at. Dui nunc mattis enim ut tellus. Diam phasellus vestibulum lorem sed risus ultricies tristique. Non nisi est sit amet facilisis. Nulla pharetra diam sit amet nisl suscipit. Vitae semper quis lectus nulla at. Pellentesque eu tincidunt tortor aliquam nulla facilisi cras fermentum. Amet porttitor eget dolor morbi non arcu risus quis. Neque egestas congue quisque egestas diam in arcu cursus. Id cursus metus aliquam eleifend. Non enim praesent elementum facilisis leo vel fringilla est ullamcorper. Eros in cursus turpis massa tincidunt.
    </div>

    <div class="division form-group">
      {{ csrf_field() }}
          <textarea name="response" class="form-control editor" rows="8" cols="80" placeholder="Write Here..." required></textarea>
    </div>
